#!/usr/bin/env python3
"""Generate docker-compose.yml from autopub/config/sites.yaml.

Usage: python3 infra/gen_compose.py [--check]
Every site gets: a WordPress container, a MariaDB database, a wp-cli helper (profile "cli"),
TLS via nginx-proxy + acme-companion. One autopub worker serves the whole fleet.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SITES_YAML = ROOT / "autopub" / "config" / "sites.yaml"
COMPOSE = ROOT / "docker-compose.yml"

HEADER = "# GENERATED by infra/gen_compose.py from autopub/config/sites.yaml - edit sites.yaml, then `make compose`.\n"


def wp_env(key: str, domain: str) -> dict:
    return {
        "WORDPRESS_DB_HOST": "db",
        "WORDPRESS_DB_NAME": f"wp_{key.lower()}",
        "WORDPRESS_DB_USER": f"wp_{key.lower()}",
        "WORDPRESS_DB_PASSWORD": f"${{WP_{key}_DB_PASSWORD}}",
        "WORDPRESS_TABLE_PREFIX": "wp_",
        "WORDPRESS_CONFIG_EXTRA": (
            f"define('WP_HOME', 'https://{domain}');\n"
            f"define('WP_SITEURL', 'https://{domain}');\n"
            "define('WP_MEMORY_LIMIT', '256M');\n"
            "define('DISALLOW_FILE_EDIT', true);\n"
            "define('WP_AUTO_UPDATE_CORE', 'minor');\n"
        ),
    }


def build(sites: list[dict]) -> dict:
    keys = [s["key"].upper() for s in sites]
    services: dict = {
        "proxy": {
            "image": "nginxproxy/nginx-proxy:1.6",
            "container_name": "proxy",
            "restart": "unless-stopped",
            "ports": ["80:80", "443:443"],
            "environment": {"TRUST_DOWNSTREAM_PROXY": "false"},
            "volumes": [
                "/var/run/docker.sock:/tmp/docker.sock:ro",
                "proxy_certs:/etc/nginx/certs",
                "proxy_vhost:/etc/nginx/vhost.d",
                "proxy_html:/usr/share/nginx/html",
                "./infra/proxy/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro",
            ],
            "networks": ["web"],
        },
        "acme": {
            "image": "nginxproxy/acme-companion:2.4",
            "restart": "unless-stopped",
            "depends_on": ["proxy"],
            "environment": {"DEFAULT_EMAIL": "${LETSENCRYPT_EMAIL}", "NGINX_PROXY_CONTAINER": "proxy"},
            "volumes": [
                "/var/run/docker.sock:/var/run/docker.sock:ro",
                "proxy_certs:/etc/nginx/certs",
                "proxy_vhost:/etc/nginx/vhost.d",
                "proxy_html:/usr/share/nginx/html",
                "acme_state:/etc/acme.sh",
            ],
            "networks": ["web"],
        },
        "db": {
            "image": "mariadb:11",
            "restart": "unless-stopped",
            "command": ["--max-allowed-packet=64M", "--innodb-buffer-pool-size=256M"],
            "environment": {
                "MARIADB_ROOT_PASSWORD": "${DB_ROOT_PASSWORD}",
                "SITE_KEYS": ",".join(keys),
                **{f"WP_{k}_DB_PASSWORD": f"${{WP_{k}_DB_PASSWORD}}" for k in keys},
            },
            "volumes": ["db_data:/var/lib/mysql", "./infra/db/init-databases.sh:/docker-entrypoint-initdb.d/10-init-databases.sh:ro"],
            "healthcheck": {"test": ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"], "interval": "10s", "timeout": "5s", "retries": 12},
            "networks": ["internal"],
        },
    }
    volumes = {"proxy_certs": {}, "proxy_vhost": {}, "proxy_html": {}, "acme_state": {}, "db_data": {}, "autopub_data": {}}

    for s in sites:
        key, domain = s["key"].upper(), s["domain"]
        slug = key.lower()
        services[f"wp_{slug}"] = {
            "image": "wordpress:6-php8.3-apache",
            "container_name": f"wp_{slug}",
            "restart": "unless-stopped",
            "depends_on": {"db": {"condition": "service_healthy"}},
            "environment": {
                **wp_env(key, domain),
                "VIRTUAL_HOST": f"{domain},www.{domain}",
                "LETSENCRYPT_HOST": f"{domain},www.{domain}",
            },
            "volumes": [f"wp_{slug}_data:/var/www/html", "./infra/wp/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro"],
            "networks": ["web", "internal"],
        }
        services[f"cli_{slug}"] = {
            "image": "wordpress:cli-php8.3",
            "profiles": ["cli"],
            "user": "33:33",
            "depends_on": {"db": {"condition": "service_healthy"}},
            "environment": wp_env(key, domain),
            "volumes": [f"wp_{slug}_data:/var/www/html"],
            "networks": ["internal", "web"],
            "entrypoint": ["wp"],
        }
        volumes[f"wp_{slug}_data"] = {}

    services["autopub"] = {
        "build": "./autopub",
        "container_name": "autopub",
        "restart": "unless-stopped",
        "env_file": [{"path": ".env", "required": False}],
        "environment": {
            "AUTOPUB_WP_INTERNAL": "true",
            "AUTOPUB_CONFIG": "/app/config/sites.yaml",
            "AUTOPUB_DATA_DIR": "/data",
            "TZ": "${TZ:-Asia/Kolkata}",
        },
        "volumes": ["autopub_data:/data", "./autopub/config:/app/config:ro"],
        "depends_on": [f"wp_{s['key'].lower()}" for s in sites],
        "networks": ["internal", "web"],
    }

    return {
        "name": "marketing-fleet",
        "services": services,
        "networks": {"web": {}, "internal": {}},
        "volumes": volumes,
    }


def render() -> str:
    with open(SITES_YAML, encoding="utf-8") as fh:
        sites = (yaml.safe_load(fh) or {}).get("sites") or []
    if not sites:
        sys.exit("no sites in sites.yaml")
    return HEADER + yaml.safe_dump(build(sites), sort_keys=False, width=1000)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if docker-compose.yml is stale")
    args = ap.parse_args()
    content = render()
    if args.check:
        current = COMPOSE.read_text(encoding="utf-8") if COMPOSE.exists() else ""
        if current != content:
            print("docker-compose.yml is out of date; run: python3 infra/gen_compose.py", file=sys.stderr)
            return 1
        print("docker-compose.yml is up to date")
        return 0
    COMPOSE.write_text(content, encoding="utf-8")
    print(f"wrote {COMPOSE.relative_to(ROOT)} for {content.count('wordpress:6-')} sites")
    return 0


if __name__ == "__main__":
    sys.exit(main())
