#!/usr/bin/env python3
"""Generate docker-compose.yml from autopub/config/sites.yaml.

Usage: python3 infra/gen_compose.py [--check]
Every site gets: a WordPress container, a MariaDB database, a wp-cli helper (profile "cli"),
TLS via nginx-proxy + acme-companion. One autopub worker serves the whole fleet.
The affiliate platform (affiliate/) is a seven-service group behind profile "affiliate": opt in with
COMPOSE_PROFILES=affiliate in .env, otherwise a plain `docker compose up -d` leaves it alone.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SITES_YAML = ROOT / "autopub" / "config" / "sites.yaml"
COMPOSE = ROOT / "docker-compose.yml"

HEADER = "# GENERATED by infra/gen_compose.py from autopub/config/sites.yaml - edit sites.yaml, then `make compose`.\n"


def wp_env(key: str, domain: str) -> dict:
    return {
        "WORDPRESS_DB_HOST": "db",
        "WORDPRESS_DB_NAME": f"wp_{key.lower()}",
        "WORDPRESS_DB_USER": f"wp_{key.lower()}",
        "WORDPRESS_DB_PASSWORD": f"${{WP_{key}_DB_PASSWORD}}",
        "WORDPRESS_TABLE_PREFIX": "wp_",
        "WORDPRESS_CONFIG_EXTRA": (
            f"define('WP_HOME', 'https://{domain}');\n"
            f"define('WP_SITEURL', 'https://{domain}');\n"
            "define('WP_MEMORY_LIMIT', '256M');\n"
            "define('DISALLOW_FILE_EDIT', true);\n"
            "define('FORCE_SSL_ADMIN', true);\n"
            "define('WP_POST_REVISIONS', 10);\n"
            "define('WP_AUTO_UPDATE_CORE', 'minor');\n"
        ),
    }


def build(sites: list[dict]) -> dict:
    keys = [s["key"].upper() for s in sites]
    services: dict = {
        "proxy": {
            "image": "nginxproxy/nginx-proxy:1.6",
            "container_name": "proxy",
            "restart": "unless-stopped",
            "ports": ["80:80", "443:443"],
            "environment": {"TRUST_DOWNSTREAM_PROXY": "false"},
            "volumes": [
                "/var/run/docker.sock:/tmp/docker.sock:ro",
                "proxy_certs:/etc/nginx/certs",
                "proxy_vhost:/etc/nginx/vhost.d",
                "proxy_html:/usr/share/nginx/html",
                "./infra/proxy/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro",
                "./infra/proxy/hardening.conf:/etc/nginx/conf.d/hardening.conf:ro",
            ],
            "networks": ["web"],
        },
        "acme": {
            "image": "nginxproxy/acme-companion:2.4",
            "restart": "unless-stopped",
            "depends_on": ["proxy"],
            "environment": {"DEFAULT_EMAIL": "${LETSENCRYPT_EMAIL}", "NGINX_PROXY_CONTAINER": "proxy"},
            "volumes": [
                "/var/run/docker.sock:/var/run/docker.sock:ro",
                "proxy_certs:/etc/nginx/certs",
                "proxy_vhost:/etc/nginx/vhost.d",
                "proxy_html:/usr/share/nginx/html",
                "acme_state:/etc/acme.sh",
            ],
            "networks": ["web"],
        },
        "db": {
            "image": "mariadb:11",
            "restart": "unless-stopped",
            "command": ["--max-allowed-packet=64M", "--innodb-buffer-pool-size=256M"],
            "environment": {
                "MARIADB_ROOT_PASSWORD": "${DB_ROOT_PASSWORD}",
                "SITE_KEYS": ",".join(keys),
                **{f"WP_{k}_DB_PASSWORD": f"${{WP_{k}_DB_PASSWORD}}" for k in keys},
            },
            "volumes": ["db_data:/var/lib/mysql", "./infra/db/init-databases.sh:/docker-entrypoint-initdb.d/10-init-databases.sh:ro"],
            "healthcheck": {"test": ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"], "interval": "10s", "timeout": "5s", "retries": 12},
            "networks": ["internal"],
        },
    }
    volumes = {"proxy_certs": {}, "proxy_vhost": {}, "proxy_html": {}, "acme_state": {}, "db_data": {}, "autopub_data": {}}

    for s in sites:
        key, domain = s["key"].upper(), s["domain"]
        slug = key.lower()
        services[f"wp_{slug}"] = {
            "image": "wordpress:6-php8.3-apache",
            "container_name": f"wp_{slug}",
            "restart": "unless-stopped",
            "depends_on": {"db": {"condition": "service_healthy"}},
            "environment": {
                **wp_env(key, domain),
                "VIRTUAL_HOST": f"{domain},www.{domain}",
                "LETSENCRYPT_HOST": f"{domain},www.{domain}",
                # one HSTS header, set at the edge (fleet-security.php deliberately sends none)
                "HSTS": "max-age=31536000; includeSubDomains",
            },
            "volumes": [f"wp_{slug}_data:/var/www/html", "./infra/wp/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro"],
            "networks": ["web", "internal"],
        }
        services[f"cli_{slug}"] = {
            "image": "wordpress:cli-php8.3",
            "profiles": ["cli"],
            "user": "33:33",
            "depends_on": {"db": {"condition": "service_healthy"}},
            "environment": wp_env(key, domain),
            "volumes": [f"wp_{slug}_data:/var/www/html"],
            "networks": ["internal", "web"],
            "entrypoint": ["wp"],
        }
        volumes[f"wp_{slug}_data"] = {}

    services["autopub"] = {
        "build": "./autopub",
        "container_name": "autopub",
        "restart": "unless-stopped",
        "env_file": [{"path": ".env", "required": False}],
        "environment": {
            "AUTOPUB_WP_INTERNAL": "true",
            "AUTOPUB_CONFIG": "/app/config/sites.yaml",
            "AUTOPUB_DATA_DIR": "/data",
            "OPENSEO_URL": "${OPENSEO_URL:-http://openseo:3001/mcp}",
            "TZ": "${TZ:-Asia/Kolkata}",
        },
        "volumes": ["autopub_data:/data", "./autopub/config:/app/config:ro"],
        "depends_on": [f"wp_{s['key'].lower()}" for s in sites],
        "networks": ["internal", "web"],
        # the publisher holds the Anthropic key and every social token: no Linux capabilities,
        # no privilege escalation, if anything in it is ever compromised
        "cap_drop": ["ALL"],
        "security_opt": ["no-new-privileges:true"],
    }

    # OpenSEO (github.com/every-app/open-seo): search data for the writer and rank tracking, self-hosted.
    # Docker mode runs with app auth off, so it is bound to the server's loopback only (reach the UI over
    # an SSH tunnel) and to the internal network, where autopub calls its MCP server at openseo:3001/mcp.
    services["openseo"] = {
        "image": "${OPEN_SEO_IMAGE:-ghcr.io/every-app/open-seo:latest}",
        "container_name": "openseo",
        "restart": "unless-stopped",
        "env_file": [{"path": ".env", "required": False}],
        "environment": {
            "CLOUDFLARE_INCLUDE_PROCESS_ENV": "true",
            "PORT": "3001",
            "AUTH_MODE": "local_noauth",
            "ALLOWED_HOST": "${OPENSEO_ALLOWED_HOST:-}",
            "DATAFORSEO_API_KEY": "${DATAFORSEO_API_KEY:-}",
            "OPENROUTER_API_KEY": "${OPENROUTER_API_KEY:-}",
            "OPENSEO_TELEMETRY_DISABLED": "${OPENSEO_TELEMETRY_DISABLED:-1}",
            "VITE_SHOW_DEVTOOLS": "false",
            "TZ": "${TZ:-Asia/Kolkata}",
        },
        "ports": ["127.0.0.1:3001:3001"],
        "volumes": ["openseo_data:/app/.wrangler"],
        "networks": ["internal", "web"],
    }
    volumes["openseo_data"] = {}

    services["pulse_worker"] = {
        "build": "./pulse-worker",
        "container_name": "pulse_worker",
        "restart": "unless-stopped",
        "env_file": [{"path": ".env", "required": False}],
        "environment": {"TZ": "${TZ:-Asia/Kolkata}"},
        "volumes": ["pulse_worker_data:/app/data", "./pulse-worker/config:/app/config"],
        "networks": ["web"],
        # holds YouTube/Meta/Reddit/Spotify/TMDB/Trakt tokens and a WordPress application password
        "cap_drop": ["ALL"],
        "security_opt": ["no-new-privileges:true"],
    }
    volumes["pulse_worker_data"] = {}

    # Affiliate platform (affiliate/, "Paparazzi"): the consumer shop, the click redirector, the v1 API and
    # its workers on their own Postgres + Redis. Opt-in: every service carries profile "affiliate", so a
    # plain `docker compose up -d` never starts it; COMPOSE_PROFILES=affiliate in .env switches it on.
    # Public hosts: AFFILIATE_WEB_HOST (shop), AFFILIATE_LINK_HOST (redirector), AFFILIATE_API_HOST (API).
    # Every ${...} has a :- default so `docker compose config` passes on .env.example; the owner fills
    # the values before opting in (an empty POSTGRES_PASSWORD stops affiliate_db, by design).
    aff_db_url = "postgresql://paparazzi:${AFFILIATE_DB_PASSWORD:-}@affiliate_db:5432/paparazzi"
    aff_redis_url = "redis://affiliate_redis:6379"
    aff_hsts = "max-age=31536000; includeSubDomains"
    # the app images hold the JWT secret and the database URL: same hardening as autopub
    aff_hardening = {"cap_drop": ["ALL"], "security_opt": ["no-new-privileges:true"]}
    aff_after_migrate = {
        "affiliate_migrate": {"condition": "service_completed_successfully"},
        "affiliate_redis": {"condition": "service_healthy"},
    }

    def aff_build(dockerfile: str, args: dict | None = None) -> dict:
        b: dict = {"context": "./affiliate", "dockerfile": f"docker/{dockerfile}"}
        if args:
            b["args"] = args
        return b

    def aff_healthz(port: int) -> dict:
        probe = f"fetch('http://localhost:{port}/healthz').then(r=>{{if(!r.ok)process.exit(1)}}).catch(()=>process.exit(1))"
        return {"test": ["CMD", "node", "-e", probe], "interval": "30s", "timeout": "5s", "retries": 3, "start_period": "20s"}

    services["affiliate_db"] = {
        "image": "postgres:16-alpine",
        "container_name": "affiliate_db",
        "profiles": ["affiliate"],
        "restart": "unless-stopped",
        "environment": {
            "POSTGRES_USER": "paparazzi",
            "POSTGRES_DB": "paparazzi",
            "POSTGRES_PASSWORD": "${AFFILIATE_DB_PASSWORD:-}",
        },
        "volumes": ["affiliate_db_data:/var/lib/postgresql/data"],
        "healthcheck": {"test": ["CMD-SHELL", "pg_isready -U paparazzi -d paparazzi"], "interval": "10s", "timeout": "5s", "retries": 5, "start_period": "10s"},
        "networks": ["internal"],
    }
    services["affiliate_redis"] = {
        "image": "redis:7-alpine",
        "container_name": "affiliate_redis",
        "profiles": ["affiliate"],
        "restart": "unless-stopped",
        "command": ["redis-server", "--appendonly", "yes"],
        "volumes": ["affiliate_redis_data:/data"],
        "healthcheck": {"test": ["CMD", "redis-cli", "ping"], "interval": "10s", "timeout": "5s", "retries": 5, "start_period": "5s"},
        "networks": ["internal"],
    }
    # One-shot: `node db/migrate.mjs` against affiliate_db, then exits; the app services wait for it.
    # The same image runs the seeds (`make affiliate-seed`): db/seed-fleet.ts reads the fleet's sites.yaml
    # and, with AFFILIATE_WEB_HOST set, reports the shop's placement id for AFFILIATE_WEB_PLACEMENT_ID.
    services["affiliate_migrate"] = {
        "build": aff_build("Dockerfile.migrate"),
        "profiles": ["affiliate"],
        "restart": "no",
        "depends_on": {"affiliate_db": {"condition": "service_healthy"}},
        "environment": {
            "DATABASE_URL": aff_db_url,
            "FLEET_SITES_YAML": "/app/config/sites.yaml",
            "AFFILIATE_WEB_HOST": "${AFFILIATE_WEB_HOST:-}",
        },
        "volumes": ["./autopub/config:/app/config:ro"],
        "networks": ["internal"],
    }
    services["affiliate_api"] = {
        "build": aff_build("Dockerfile.api"),
        "container_name": "affiliate_api",
        "profiles": ["affiliate"],
        "restart": "unless-stopped",
        "depends_on": aff_after_migrate,
        "environment": {
            "NODE_ENV": "production",
            "API_HOST": "0.0.0.0",
            "API_PORT": "3000",
            "DATABASE_URL": aff_db_url,
            "REDIS_URL": aff_redis_url,
            "JWT_SECRET": "${AFFILIATE_JWT_SECRET:-}",
            "REDIRECT_BASE_URL": "https://${AFFILIATE_LINK_HOST:-}",
            "VIRTUAL_HOST": "${AFFILIATE_API_HOST:-}",
            "VIRTUAL_PORT": "3000",
            "LETSENCRYPT_HOST": "${AFFILIATE_API_HOST:-}",
            "HSTS": aff_hsts,
        },
        "healthcheck": aff_healthz(3000),
        "networks": ["web", "internal"],
        **aff_hardening,
    }
    services["affiliate_redirect"] = {
        "build": aff_build("Dockerfile.redirect"),
        "container_name": "affiliate_redirect",
        "profiles": ["affiliate"],
        "restart": "unless-stopped",
        "depends_on": aff_after_migrate,
        "environment": {
            "NODE_ENV": "production",
            "REDIRECT_PORT": "3001",
            "DATABASE_URL": aff_db_url,
            "REDIS_URL": aff_redis_url,
            "VIRTUAL_HOST": "${AFFILIATE_LINK_HOST:-}",
            "VIRTUAL_PORT": "3001",
            "LETSENCRYPT_HOST": "${AFFILIATE_LINK_HOST:-}",
            "HSTS": aff_hsts,
        },
        "healthcheck": aff_healthz(3001),
        "networks": ["web", "internal"],
        **aff_hardening,
    }
    services["affiliate_workers"] = {
        "build": aff_build("Dockerfile.workers"),
        "container_name": "affiliate_workers",
        "profiles": ["affiliate"],
        "restart": "unless-stopped",
        "depends_on": aff_after_migrate,
        "environment": {
            "NODE_ENV": "production",
            "DATABASE_URL": aff_db_url,
            "REDIS_URL": aff_redis_url,
            "STUB_WEBHOOK_SECRET": "${AFFILIATE_STUB_WEBHOOK_SECRET:-}",
            # 365-day placeholders until counsel sets the real windows (affiliate/.env.prod.example)
            "RETENTION_CLICK_CONTEXT_DAYS": "${AFFILIATE_RETENTION_CLICK_CONTEXT_DAYS:-365}",
            "RETENTION_CONVERSION_RAW_DAYS": "${AFFILIATE_RETENTION_CONVERSION_RAW_DAYS:-365}",
            "RETENTION_OUTBOX_DAYS": "${AFFILIATE_RETENTION_OUTBOX_DAYS:-365}",
            "RETENTION_CRON": "${AFFILIATE_RETENTION_CRON:-0 3 * * *}",
        },
        "networks": ["internal"],
        **aff_hardening,
    }
    # The shop. Browser calls go to /api on its own host (baked in at build time) and the server side
    # reaches the API over the internal network, so the API host never has to be public for the shop.
    services["affiliate_web"] = {
        "build": aff_build("Dockerfile.web", {"NEXT_PUBLIC_API_BASE": "/api"}),
        "container_name": "affiliate_web",
        "profiles": ["affiliate"],
        "restart": "unless-stopped",
        "depends_on": ["affiliate_api"],
        "environment": {
            "NODE_ENV": "production",
            "API_BASE": "http://affiliate_api:3000",
            "WEB_API_TOKEN": "${AFFILIATE_WEB_API_TOKEN:-}",
            "WEB_PLACEMENT_ID": "${AFFILIATE_WEB_PLACEMENT_ID:-}",
            "NEXT_PUBLIC_SITE_NAME": "${AFFILIATE_SITE_NAME:-Paparazzi Commerce}",
            "VIRTUAL_HOST": "${AFFILIATE_WEB_HOST:-}",
            "VIRTUAL_PORT": "3000",
            "LETSENCRYPT_HOST": "${AFFILIATE_WEB_HOST:-}",
            "HSTS": aff_hsts,
        },
        "networks": ["web", "internal"],
        **aff_hardening,
    }
    volumes["affiliate_db_data"] = {}
    volumes["affiliate_redis_data"] = {}

    return {
        "name": "marketing-fleet",
        "services": services,
        "networks": {"web": {}, "internal": {}},
        "volumes": volumes,
    }


def render() -> str:
    with open(SITES_YAML, encoding="utf-8") as fh:
        sites = (yaml.safe_load(fh) or {}).get("sites") or []
    if not sites:
        sys.exit("no sites in sites.yaml")
    return HEADER + yaml.safe_dump(build(sites), sort_keys=False, width=1000)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if docker-compose.yml is stale")
    args = ap.parse_args()
    content = render()
    if args.check:
        current = COMPOSE.read_text(encoding="utf-8") if COMPOSE.exists() else ""
        if current != content:
            print("docker-compose.yml is out of date; run: python3 infra/gen_compose.py", file=sys.stderr)
            return 1
        print("docker-compose.yml is up to date")
        return 0
    COMPOSE.write_text(content, encoding="utf-8")
    print(f"wrote {COMPOSE.relative_to(ROOT)} for {content.count('wordpress:6-')} sites")
    return 0


if __name__ == "__main__":
    sys.exit(main())
