import { sha256Hex } from './hash.js';

/**
 * Version of the event envelope schema. Bump on any breaking change to
 * `EventEnvelope`; consumers can branch on it for forward compatibility.
 */
export const EVENT_SCHEMA_VERSION = '1.0' as const;

/** Canonical envelope for every domain event published on the outbox / queues. */
export interface EventEnvelope {
  schema_version: typeof EVENT_SCHEMA_VERSION;
  /** Random UUID v4 generated by `buildEnvelope`. */
  event_id: string;
  /** Originating subsystem, e.g. 'api', 'redirect', 'workers'. */
  source: string;
  /** Provider/connector account that produced the event, if applicable. */
  source_account_id: string | null;
  /** When the underlying fact happened (ISO 8601). */
  occurred_at: string;
  /** When this envelope was built (ISO 8601). */
  received_at: string;
  /** Dotted event name, e.g. 'conversion.received'. */
  event_type: string;
  /** `hashPayload(payload)` — lets consumers detect tampering / dedupe. */
  payload_hash: string;
  payload: unknown;
}

/**
 * Deterministic serialisation: objects have their keys sorted recursively,
 * arrays keep order, `undefined` object values are dropped (matching
 * `JSON.stringify` semantics), and non-finite numbers throw.
 */
export function canonicalJson(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error('canonicalJson: non-finite number');
    return JSON.stringify(value);
  }
  if (typeof value === 'string' || typeof value === 'boolean') {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return '[' + value.map(canonicalJson).join(',') + ']';
  }
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>;
    const keys = Object.keys(record)
      .filter((k) => record[k] !== undefined)
      .sort();
    return '{' + keys.map((k) => JSON.stringify(k) + ':' + canonicalJson(record[k])).join(',') + '}';
  }
  throw new Error(`canonicalJson: unsupported type ${typeof value}`);
}

/** SHA-256 hex of the canonical JSON form of `payload`. */
export function hashPayload(payload: unknown): string {
  return sha256Hex(canonicalJson(payload));
}

function randomBytes(count: number): number[] {
  const g = (globalThis as { crypto?: { getRandomValues(a: Uint8Array): Uint8Array } }).crypto;
  const buf = new Uint8Array(count);
  if (g && typeof g.getRandomValues === 'function') {
    g.getRandomValues(buf);
  } else {
    // Non-crypto fallback for exotic runtimes; event ids are not secrets.
    for (let i = 0; i < count; i++) buf[i] = Math.floor(Math.random() * 256);
  }
  return Array.from(buf);
}

/** Random UUID v4 (RFC 4122) for `event_id`. */
export function newEventId(): string {
  const b = randomBytes(16);
  b[6] = (b[6]! & 0x0f) | 0x40; // version 4
  b[8] = (b[8]! & 0x3f) | 0x80; // variant 10xxxxxx
  const hex = b.map((x) => x.toString(16).padStart(2, '0')).join('');
  return (
    hex.slice(0, 8) + '-' + hex.slice(8, 12) + '-' + hex.slice(12, 16) + '-' + hex.slice(16, 20) + '-' + hex.slice(20)
  );
}

export interface BuildEnvelopeParams {
  source: string;
  source_account_id?: string | null;
  event_type: string;
  payload: unknown;
  /** Defaults to now. */
  occurred_at?: string;
}

export function buildEnvelope(params: BuildEnvelopeParams): EventEnvelope {
  const now = new Date().toISOString();
  return {
    schema_version: EVENT_SCHEMA_VERSION,
    event_id: newEventId(),
    source: params.source,
    source_account_id: params.source_account_id ?? null,
    occurred_at: params.occurred_at ?? now,
    received_at: now,
    event_type: params.event_type,
    payload_hash: hashPayload(params.payload),
    payload: params.payload,
  };
}
