#!/usr/bin/env bash
# Afflino: the owner's celebrity-look steps on the Linode, one line each.
# Run as root on the Linode, after the installer (docs/runbooks/deploy.md,
# "Celebrity looks", has the order and what to expect):
#
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh owned         record your statement that you own the library's
#                                                                    footage (the legal owner's name, who shot it; dated):
#                                                                    rows without licence columns then take it
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh owned withdraw   end it: what it licensed shows no image at once
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh import        the paparazzi library file → draft looks,
#                                                                    celebrities (unreviewed), assets with licences
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh status        counts: celebrities, looks, takedowns, replies
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh celebrities   each celebrity's page name (slug) and status
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh review        record counsel's decision for one celebrity
#                                                                    (asked at prompts; the evidence reference required)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh takedown      withdraw a celebrity (every look) or one look NOW:
#                                                                    410 everywhere, links paused, replies off
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh takedowns     the takedowns, with the time each took to act
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh restore       lift a takedown (after a new review)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh storefronts   a draft storefront for every in-house page, and
#                                                                    each page's bio URL (afflino.com/s/<slug>)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh storefronts live   every draft storefront public (live)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh keys          the Meta app secret, a verify token you make up, the
#                                                                    system user's token (hidden prompts; never printed)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh webhook       what to enter in Meta's App Dashboard: the webhook
#                                                                    address and fields (feed, comments, messages, …), the
#                                                                    data-deletion address (no secret is shown)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh reply-test    one look's exact private reply through the stub
#                                                                    sender (nothing sent to Meta) and the webhook's
#                                                                    own checks (verify, signed, wrongly signed)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh events        the latest comment-reply events (no personal data)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh signin        an 8-hour sign-in for the admin (/login), written to
#                                                                    /etc/afflino/admin-sign-in.token (0600), never printed;
#                                                                    your Mac copies it to the clipboard (the runbook's line)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh accounts      map the Facebook pages and Instagram accounts to
#                                                                    their Meta ids and subscribe the pages' webhooks
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh replies off   comment replies: off | shadow (every check, no send) |
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh replies shadow on (refused while /privacy is the stub page)
#   bash /opt/afflino/affiliate/deploy/linode/looks.sh replies on
#
# Files (outside the checkout, so updates keep working):
#   /etc/afflino/afflino.env                 META_APP_SECRET, META_VERIFY_TOKEN, META_SYSTEM_USER_TOKEN (keys),
#                                            COMMENT_REPLIES_SENDING (replies); COMMENT_ID_HASH_KEY and
#                                            WEB_REVALIDATE_SECRET are generated by the installer
#   /etc/afflino/library/library.csv         the library file (the columns: packages/api/src/looks/library-import.ts;
#                                            the TEST example: db/fixtures/library.example.csv)
#   /etc/afflino/library/storefronts.csv     optional: platform,account,slug,display_name[,bio][,status]
#   /etc/afflino/library/*.json              the last answers, written here (0600)
#
# Nothing here is a legal conclusion: `review` records what counsel decided
# (as the organisation's rights reviewer), `takedown` acts on a notice at
# once and records when it arrived. Real celebrity names and library data
# live in these files and in the database on the server, never in the
# repository.
#
# Secrets are read at hidden prompts (from standard input; on a terminal
# nothing is echoed), written only to /etc/afflino/afflino.env (root:root
# 0600) and never printed, logged or put on a command line.
#
# TEST-ONLY settings (rehearsing this script off the Linode; never needed there):
#   AFFLINO_DIR=/opt/afflino  AFFLINO_ENV_FILE=/etc/afflino/afflino.env  AFFLINO_PROJECT=afflino
#   AFFLINO_EDGE_TEST=1  AFFLINO_EXTRA_COMPOSE_FILE=f     as for install.sh
#   AFFLINO_LIBRARY_DIR=/etc/afflino/library              the files above
#   AFFLINO_WEB_URL=http://127.0.0.1:3002                 where `replies on` reads /privacy
#   AFFLINO_LOOKS_ALLOW_TEST_VALUES=1                     let the CLI accept TEST rows ("Demo …",
#                                                         example.com): it runs with NODE_ENV=development
#   AFFLINO_LOOKS_SKIP_PRIVACY_CHECK=1                    let `replies on` run while /privacy is the stub

set -Eeuo pipefail

main() {
  local DIR="${AFFLINO_DIR:-/opt/afflino}"
  local ENV_FILE="${AFFLINO_ENV_FILE:-/etc/afflino/afflino.env}"
  local PROJECT="${AFFLINO_PROJECT:-afflino}"
  local LIB="${AFFLINO_LIBRARY_DIR:-/etc/afflino/library}"
  local WEB="${AFFLINO_WEB_URL:-http://127.0.0.1:3002}"
  local APP="$DIR/affiliate"
  local SELF_LINE="bash $APP/deploy/linode/looks.sh"
  local UPDATE_LINE="bash <(curl -fsSL https://raw.githubusercontent.com/sudhanshu6454/sud/refs/heads/claude/nifty-pasteur-flrulw/affiliate/deploy/linode/install.sh)"
  local cmd="${1:-}"

  say()  { printf '%s\n' "$*"; }
  info() { printf '   %s\n' "$*"; }
  warn() { printf '   WARNING: %s\n' "$*" >&2; }
  die()  { printf '\nSTOPPED: %s\n' "$*" >&2; exit 1; }
  next() { printf '\nNext: %s\n' "$*"; }
  have() { command -v "$1" >/dev/null 2>&1; }
  is_on() { case "${1:-}" in 1|yes|true|on) return 0 ;; *) return 1 ;; esac; }
  ask()  { # $1 prompt; the answer on stdout (visible: never a secret)
    local a
    printf '   %s' "$1" >&2
    IFS= read -r a || a=""
    printf '%s' "$a"
  }

  case "$cmd" in
    owned|import|status|celebrities|review|takedown|takedowns|restore|storefronts|keys|webhook|accounts|replies|reply-test|events|signin) ;;
    *)
      say "usage: $SELF_LINE owned [withdraw]|import|status|celebrities|review|takedown|takedowns|restore|storefronts [live]|keys|webhook|accounts|replies off|shadow|on|reply-test|events|signin"
      say "(docs/runbooks/deploy.md, \"Celebrity looks\", has the order)"
      [ -z "$cmd" ] && exit 2
      die "unknown step '$cmd'"
      ;;
  esac

  [ "$(id -u)" -eq 0 ] || die "run this as root on the Linode."
  [ -f "$APP/docker-compose.prod.yml" ] || die "no Afflino checkout at $APP (run the installer first: $UPDATE_LINE)"
  [ -f "$ENV_FILE" ] || die "no $ENV_FILE (run the installer first: $UPDATE_LINE)"
  have docker || die "docker is not installed (run the installer first)"
  have python3 || die "python3 is not installed"

  # ------------------------------------------------------------ env file
  env_get() {
    local line v
    line="$(grep -E "^[[:space:]]*$1=" "$ENV_FILE" | tail -n 1 || true)"
    v="${line#*=}"
    case "$v" in \"*\") v="${v#\"}"; v="${v%\"}" ;; \'*\') v="${v#\'}"; v="${v%\'}" ;; esac
    printf '%s' "$v"
  }
  # Replace (or add) KEY=VALUE lines in one atomic write, root:root 0600. Values are never printed.
  env_set() {
    local dir tmp k v keep
    dir="$(dirname "$ENV_FILE")"
    tmp="$(mktemp "$dir/.afflino.env.XXXXXX")"
    chmod 600 "$tmp"
    keep="$(grep -v '^# Set by deploy/linode/looks.sh on ' "$ENV_FILE" || true)"
    local args=("$@") i
    for ((i = 0; i < ${#args[@]}; i += 2)); do
      k="${args[i]}"
      keep="$(printf '%s\n' "$keep" | grep -Ev "^[[:space:]]*$k=" || true)"
    done
    {
      printf '%s\n' "$keep"
      printf '# Set by deploy/linode/looks.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
      for ((i = 0; i < ${#args[@]}; i += 2)); do
        k="${args[i]}"; v="${args[i + 1]}"
        printf '%s=%s\n' "$k" "$v"
      done
    } >"$tmp"
    chown root:root "$tmp" 2>/dev/null || true
    mv -f "$tmp" "$ENV_FILE"
  }
  safe_value() { printf '%s' "$1" | grep -Eq '^[A-Za-z0-9._~+/=:@,-]+$'; }

  # --------------------------------------------------------------- compose
  local files=(-f "$APP/docker-compose.prod.yml" -f "$APP/docker-compose.single-host.yml")
  if is_on "${AFFLINO_EDGE_TEST:-}"; then files+=(-f "$APP/docker-compose.edge-test.yml"); fi
  if [ -n "${AFFLINO_EXTRA_COMPOSE_FILE:-}" ]; then files+=(-f "$AFFLINO_EXTRA_COMPOSE_FILE"); fi
  # As install.sh: the environment file is the only source of the stack's variables.
  local unset_args=() key
  while IFS= read -r key; do
    unset_args+=(-u "$key")
  done < <(grep -Eo '^[A-Z][A-Z0-9_]*=' "$APP/.env.prod.example" | tr -d '=' | sort -u; printf '%s\n' COMPOSE_FILE COMPOSE_PROJECT_NAME COMPOSE_PROFILES)
  dc() { env "${unset_args[@]}" docker compose --project-directory "$APP" -p "$PROJECT" --env-file "$ENV_FILE" "${files[@]}" "$@"; }
  local node_env_args=()
  if is_on "${AFFLINO_LOOKS_ALLOW_TEST_VALUES:-}"; then
    node_env_args=(-e NODE_ENV=development)
    warn "AFFLINO_LOOKS_ALLOW_TEST_VALUES: the CLI accepts TEST rows (test only; never on the Linode)"
  fi
  # The api image's looks CLI (node dist/cli/looks.js) with the library directory
  # mounted read-only at /app/config/library. Standard input is never handed to the container.
  cli() {
    dc run --rm --no-deps -T -v "$LIB:/app/config/library:ro" "${node_env_args[@]}" api node dist/cli/looks.js "$@" </dev/null
  }
  stack_up() {
    [ -n "$(dc ps -q --status running api 2>/dev/null)" ] || die "the api is not running (run the installer line first: $UPDATE_LINE)"
  }
  share_inputs() {
    install -d -m 0755 "$LIB"
    find "$LIB" -maxdepth 1 -type f -name '*.csv' -exec chmod 0644 {} +
  }
  keep_json() { # $1 file: owner-only
    chmod 0600 "$1" 2>/dev/null || true
  }
  privacy_gate() {
    if is_on "${AFFLINO_LOOKS_SKIP_PRIVACY_CHECK:-}"; then
      warn "AFFLINO_LOOKS_SKIP_PRIVACY_CHECK: the privacy-notice check is skipped (test only; never on the Linode)"
      return 0
    fi
    local body code
    body="$(mktemp)"
    code="$(curl -s --noproxy '*' --max-time 15 -o "$body" -w '%{http_code}' "$WEB/privacy" || true)"
    if [ "$code" != 200 ]; then
      rm -f "$body"
      die "the site's /privacy page did not answer (HTTP ${code:-none} from $WEB); is the web running?"
    fi
    if grep -q 'data-document-status="stub"' "$body"; then
      rm -f "$body"
      die "afflino.com/privacy is still the stub page. Meta requires a public privacy policy covering what comment replies process and how to ask for deletion (and App Review needs its URL): counsel's text goes on /privacy first; nothing was changed"
    fi
    rm -f "$body"
  }
  restart_workers() {
    local upout
    upout="$(dc up -d --no-deps workers 2>&1)" || { printf '%s\n' "$upout" >&2; die "the workers did not restart (above)"; }
  }

  case "$cmd" in
    # ---------------------------------------------------------------- import
    import)
      stack_up
      share_inputs
      [ -s "$LIB/library.csv" ] || die "no $LIB/library.csv yet (the columns: docs/runbooks/deploy.md, \"Celebrity looks\"; the example: $APP/db/fixtures/library.example.csv)"
      local out="$LIB/import.json"
      if ! cli import --file /app/config/library/library.csv >"$out.new"; then
        rm -f "$out.new"
        die "the library file was refused (the reasons are above); nothing was written"
      fi
      mv -f "$out.new" "$out"; keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
print(f"   {s['rows']} row(s), {s['looks']} look(s): {s['looks_created']} new (drafts), {s['looks_updated']} updated, {s['looks_unchanged']} unchanged, {s['looks_not_draft_kept']} kept (no longer drafts)")
print(f"   celebrities: {s['celebrities_created']} new (unreviewed: nothing about them is published until a review), {s['celebrities_matched']} matched, {s['celebrities_flagged_minor']} flagged minors")
print(f"   assets: {s['assets_created']} new, {s['assets_updated']} updated; pieces: {s['pieces_created']} new, {s['pieces_updated']} updated")
st = s.get("ownership_statement")
if s.get("licence_from_statement"):
    rest = s['looks'] - s['licence_from_statement']
    print(f"   licence: {s['licence_from_statement']} look(s) from your ownership statement of {st['recorded_at'][:10]} ({st['copyright_owner']}){f'; {rest} from their own licence columns' if rest else ''}")
for k in s.get("licence_kept", []):
    print(f"   kept as a person set it (the file would widen {', '.join(k['kept'])}): {k['kind']} {k['ref']}")
PY
      next "$SELF_LINE celebrities, then counsel's decision for each: $SELF_LINE review"
      ;;

    # ---------------------------------------------------------------- owned
    owned)
      local omode="${2:-}"
      case "$omode" in ""|withdraw) ;; *) die "usage: $SELF_LINE owned   or   $SELF_LINE owned withdraw" ;; esac
      stack_up
      install -d -m 0755 "$LIB"
      local out="$LIB/ownership.json" cur="$LIB/ownership-now.json"
      cli ownership >"$cur" || die "could not read the ownership statement (above)"
      keep_json "$cur"
      python3 - "$cur" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
st = s["statement"]
if st:
    print(f"   In force: recorded {st['recorded_at'][:10]}, copyright owner {st['copyright_owner']} ({'own employees' if st['acquisition'] == 'staff' else 'employees, freelancers and agencies'})")
else:
    print("   No ownership statement is in force: library rows need their own licence columns.")
for a in s["assets_by_licence"]:
    print(f"   assets licensed by {a['via']}: {a['assets']} ({a['commercial_reuse']} commercial reuse)")
PY
      if [ "$omode" = withdraw ]; then
        say "Withdraw the statement: every clip and still licensed by it goes back to an unknown licence at once"
        say "(no image of it is shown), and library rows without licence columns are refused until a new one."
        local reason confirm
        reason="$(ask 'Why (one line, at least 10 characters): ')"
        confirm="$(ask 'Type withdraw to confirm: ')"
        [ "$confirm" = withdraw ] || die "not confirmed; nothing changed"
        cli ownership --withdraw yes --reason "$reason" >"$out" || die "the withdrawal was refused (the reason is above); nothing changed"
        keep_json "$out"
        python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
print(f"   Withdrawn. {s['assets_narrowed']} asset(s) back to an unknown licence; their images are no longer shown.")
PY
        return 0
      fi
      say "Record your statement that you own the library's footage. Every library row without licence"
      say "columns then takes this licence: commercial use allowed, worldwide, no end date. A row that fills"
      say "its licence columns keeps its own. This covers the footage only: each celebrity's own rights stay"
      say "with counsel's review (the review step); nothing about a celebrity is shown without one."
      local name who acq preview confirm
      name="$(ask 'The legal name of the company (or person) that owns the footage: ')"
      say "   Who shot the clips?"
      say "     1  our own employees only"
      say "     2  our employees, and freelancers or agencies working for us"
      who="$(ask 'Choice [1-2]: ')"
      case "$who" in 1) acq=staff ;; 2) acq=other ;; *) die "1 or 2; nothing was recorded" ;; esac
      preview="$(mktemp)"
      if ! cli ownership --preview yes --copyright-owner "$name" --acquisition "$acq" >"$preview"; then
        rm -f "$preview"
        die "not recorded (the reason is above)"
      fi
      say ""
      say "   Your statement:"
      python3 -c 'import json, sys, textwrap; print(textwrap.fill(json.load(open(sys.argv[1]))["statement"], 96, initial_indent="     ", subsequent_indent="     "))' "$preview"
      rm -f "$preview"
      confirm="$(ask 'Type yes to record it as your statement, dated today: ')"
      [ "$confirm" = yes ] || die "not confirmed; nothing was recorded"
      cli ownership --record yes --copyright-owner "$name" --acquisition "$acq" >"$out" || die "not recorded (the reason is above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
st = s["statement"]
print(f"   Recorded {st['recorded_at'][:10]} (statement {st['seq']}){'; it replaces the one before' if s['superseded'] else ''}.")
PY
      next "$SELF_LINE import (rows without licence columns take this licence)"
      ;;

    # --------------------------------------------------------------- status
    status)
      stack_up
      install -d -m 0755 "$LIB"
      local out="$LIB/status.json"
      cli status >"$out" || die "no status (above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
for k in ["celebrities_by_status", "looks_by_status", "items_by_match", "takedowns_by_status", "storefronts_by_status", "reply_rules", "reply_events_by_status", "meta_accounts_by_status"]:
    print(f"   {k.replace('_', ' ')}: {json.dumps(s[k]) if s[k] else 'none'}")
PY
      ;;

    # ---------------------------------------------------------- celebrities
    celebrities)
      stack_up
      install -d -m 0755 "$LIB"
      local out="$LIB/celebrities.json"
      cli celebrities >"$out" || die "no list (above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
items = json.load(open(sys.argv[1]))["items"]
if not items:
    print("   no celebrity yet: import the library first")
for c in items:
    e = c["effective"]
    flags = ", ".join(f for f in (["MINOR"] if c["is_minor"] else []) + (["never-list"] if c["never_list"] else []) + (["UNDER TAKEDOWN"] if c["takedown_id"] else []))
    print(f"   {c['slug']:<32} {c['rights_status']:<11} shows: {e['display']}{', products' if e['shoppable'] else ''}{'  [' + flags + ']' if flags else ''}")
PY
      ;;

    # --------------------------------------------------------------- review
    review)
      stack_up
      say "Record counsel's decision for one celebrity (you are recording it as the rights reviewer)."
      local slug status disp="" shop="no" ref note
      slug="$(ask 'Celebrity (the slug from the celebrities step): ')"
      printf '%s' "$slug" | grep -Eq '^[a-z0-9]+(-[a-z0-9]+)*$' || die "'$slug' is not a slug (letters, digits and hyphens); nothing changed"
      say "   Status: unreviewed | editorial (name only, no products) | cleared (counsel cleared a page with products) | blocked"
      status="$(ask 'Status: ')"
      case "$status" in unreviewed|editorial|cleared|blocked) ;; *) die "the status is unreviewed, editorial, cleared or blocked; nothing changed" ;; esac
      if [ "$status" = cleared ]; then
        disp="$(ask 'May the photo be shown? (yes/no): ')"
        case "$disp" in yes) disp=name_and_image ;; no) disp=name_only ;; *) die "yes or no; nothing changed" ;; esac
        shop="$(ask 'May a page naming them carry products and links? (yes/no): ')"
        case "$shop" in yes|no) ;; *) die "yes or no; nothing changed" ;; esac
      fi
      ref="$(ask "Evidence reference (counsel's advice or the licence, e.g. its file or email reference): ")"
      note="$(ask 'Note (one line): ')"
      local out="$LIB/review.json" args=(review --celebrity "$slug" --status "$status")
      [ -n "$disp" ] && args+=(--max-display "$disp")
      args+=(--shoppable "$shop")
      [ -n "$ref" ] && args+=(--evidence-ref "$ref")
      [ -n "$note" ] && args+=(--note "$note")
      install -d -m 0755 "$LIB"
      cli "${args[@]}" >"$out" || die "the review was refused (the reason is above); nothing changed"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
c = s["celebrity"]; e = c["effective"]
print(f"   {c['name']}: {c['rights_status']}; shows {e['display']}{' with products' if e['shoppable'] else ', no products'}")
if s["links_paused"]: print(f"   {s['links_paused']} link(s) of their looks paused (no shoppable page any more)")
if s["links_reactivated"]: print(f"   {s['links_reactivated']} link(s) of their published looks active again")
PY
      ;;

    # ------------------------------------------------------------- takedown
    takedown)
      stack_up
      say "Take down NOW: every public page of a celebrity (or one look) answers 410 at once, its links pause,"
      say "its comment replies stop. A restore later needs a new review."
      local what target reason ref when note out="$LIB/takedown.json" args=(takedown)
      what="$(ask 'A whole celebrity or one look? (celebrity/look): ')"
      case "$what" in
        celebrity)
          target="$(ask 'Celebrity (the slug): ')"
          printf '%s' "$target" | grep -Eq '^[a-z0-9]+(-[a-z0-9]+)*$' || die "'$target' is not a slug; nothing changed"
          args+=(--celebrity "$target") ;;
        look)
          target="$(ask "The look's id (from the admin, or the look page's address): ")"
          target="${target##*/}"
          printf '%s' "$target" | grep -Eq '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' || die "'$target' is not a look id; nothing changed"
          args+=(--look "$target") ;;
        *) die "celebrity or look; nothing changed" ;;
      esac
      say "   Reason: rights_holder_request | legal_notice | court_order | licence_expired | privacy_request | counsel_instruction | operator_error | other"
      reason="$(ask 'Reason: ')"
      case "$reason" in rights_holder_request|legal_notice|court_order|licence_expired|privacy_request|counsel_instruction|operator_error|other) ;; *) die "not one of the reasons; nothing changed" ;; esac
      ref="$(ask "The notice's reference (no names, just its number or file reference; Enter for none): ")"
      when="$(ask 'When it was received, in UTC as 2026-09-30T14:05 (Enter for now): ')"
      if [ -n "$when" ]; then
        printf '%s' "$when" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}$' || die "the time is YYYY-MM-DDTHH:MM (UTC); nothing changed"
        args+=(--requested-at "${when}:00Z")
      fi
      note="$(ask 'Note (one line; Enter for none): ')"
      args+=(--reason "$reason")
      [ -n "$ref" ] && args+=(--requester-ref "$ref")
      [ -n "$note" ] && args+=(--note "$note")
      install -d -m 0755 "$LIB"
      cli "${args[@]}" >"$out" || die "the takedown did not run (the reason is above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
t = s["takedown"]
print(f"   takedown {t['id']} {'(already active: nothing more to do)' if not s['created'] else ''}")
print(f"   {s['looks_withdrawn']} look(s) withdrawn (410 on every public page), {s['links_paused']} link(s) paused, {s['rules_disabled']} comment-reply rule(s) off, {s['replies_cancelled']} queued repl(y/ies) cancelled")
named = s.get("looks_named_in_text") or []
if named:
    print(f"   {len(named)} other look(s) whose text names this person withdrawn too")
if s.get("other_links_paused"):
    print(f"   {s['other_links_paused']} other page link(s) for these looks' products on their pages paused")
print(f"   notice received {t['requested_at']}, acted {t['actioned_at']} ({t['minutes_to_action']} min), caches cleared {t['completed_at']}")
posts = s["posts_to_delete"]
if posts:
    print("   1. DELETE these in-house posts on Facebook / Instagram yourself (Afflino cannot):")
    for p in posts:
        print(f"     {p['platform']}/{p['account']}: {p['post_permalink'] or p['platform_post_id']}")
share = s.get("share_urls") or []
if share:
    print("   2. Link previews: in Meta's Sharing Debugger (developers.facebook.com/tools/debug), paste each address and press Scrape Again:")
    for u in share:
        print(f"     {u}")
stills = s.get("stills") or []
if stills:
    print("   3. The stills (their afflino.com address answers 410 now; if counsel asks, remove the origin files too):")
    for st in stills:
        print(f"     look {st['look_id']}: {st['source_ref'] or st['asset_id']}")
PY
      next "delete the posts above on Meta and scrape the addresses again; the list: $SELF_LINE takedowns"
      ;;

    # ------------------------------------------------------------ takedowns
    takedowns)
      stack_up
      install -d -m 0755 "$LIB"
      local out="$LIB/takedowns.json"
      cli takedowns >"$out" || die "no list (above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
items = json.load(open(sys.argv[1]))["items"]
if not items:
    print("   no takedown")
for t in items:
    print(f"   {t['id']}  {t['status']:<8} {t['scope']:<9} {t['reason_code']:<22} received {t['requested_at']}  acted in {t['minutes_to_action']} min [{t['sla']}]  looks {t['looks_withdrawn']}, links {t['links_paused']}")
PY
      ;;

    # -------------------------------------------------------------- restore
    restore)
      stack_up
      say "Lift a takedown. It needs a new review of the celebrity recorded after the takedown ($SELF_LINE review)."
      local id note out="$LIB/restore.json"
      id="$(ask 'The takedown id (from the takedowns step): ')"
      printf '%s' "$id" | grep -Eq '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' || die "'$id' is not a takedown id; nothing changed"
      note="$(ask 'Why it is lifted (one line): ')"
      [ -n "$note" ] || die "a note is required; nothing changed"
      install -d -m 0755 "$LIB"
      cli restore --takedown "$id" --note "$note" >"$out" || die "the restore was refused (the reason is above); nothing changed"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
for l in s["looks"]:
    print(f"   look {l['look_id']}: {l['status']}")
print(f"   {s['links_reactivated']} link(s) active again; comment replies stay off until an editor turns them on")
PY
      ;;

    # ---------------------------------------------------------- storefronts
    storefronts)
      local sfmode="${2:-}"
      case "$sfmode" in ""|live) ;; *) die "usage: $SELF_LINE storefronts   or   $SELF_LINE storefronts live" ;; esac
      stack_up
      share_inputs
      local out="$LIB/storefronts.json" args=(storefronts)
      [ -s "$LIB/storefronts.csv" ] && args+=(--file /app/config/library/storefronts.csv)
      [ "$sfmode" = live ] && args+=(--publish yes)
      cli "${args[@]}" >"$out" || die "the storefronts step failed (above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
print(f"   {s['created']} created (drafts), {s['updated']} updated, {s.get('published', 0)} made live; by status: {json.dumps(s['storefronts_by_status'])}")
for r in s["refused"][:20]:
    print(f"   refused: {r}")
fronts = s.get("storefronts", [])
if fronts:
    print("   Each page's bio link (put it in the page's bio; it works once the storefront is live):")
for f in fronts:
    print(f"   {f['status']:<6} {f['platform']:<9} {f['account']:<32} {f['bio_url']}")
PY
      if [ "$sfmode" = live ]; then
        info "a live storefront shows only public looks (the rights gate); a page with none shows an empty page"
      else
        info "a storefront is public only once live: $SELF_LINE storefronts live (or a status column in $LIB/storefronts.csv)"
      fi
      ;;

    # ----------------------------------------------------------------- keys
    keys)
      say "Comment-reply settings in $ENV_FILE (values are never printed)"
      local v pairs=() set_names=() name label
      for name in META_APP_SECRET META_VERIFY_TOKEN META_SYSTEM_USER_TOKEN; do
        case "$name" in
          META_APP_SECRET) label="the Meta app's App Secret (App settings > Basic)" ;;
          META_VERIFY_TOKEN) label="a verify token you make up (16+ letters or digits; you type the same string into Meta's dashboard in the webhook step; it is never shown)" ;;
          *) label="the system user's token (Business settings > System users > Generate token)" ;;
        esac
        if [ -n "$(env_get "$name")" ]; then
          printf '\n   %s, hidden. Press Enter to keep the one already set: ' "$label" >&2
        else
          printf '\n   %s, hidden. Press Enter to skip: ' "$label" >&2
        fi
        IFS= read -r -s v || v=""
        printf '\n' >&2
        v="$(printf '%s' "$v" | tr -d '[:space:]')"
        if [ -n "$v" ]; then
          safe_value "$v" || die "that value has characters the environment file cannot hold; nothing changed"
          [ "${#v}" -ge 16 ] || die "that value is shorter than 16 characters; nothing changed"
          pairs+=("$name" "$v"); set_names+=("$name")
        fi
        v=""
      done
      if [ "${#pairs[@]}" -gt 0 ]; then
        env_set "${pairs[@]}"
        pairs=()
        info "set in $ENV_FILE (root:root 0600): ${set_names[*]}"
        local host
        host="$(env_get SITE_HOST)"
        info "Meta's webhook callback: https://${host:-afflino.com}/api/v1/integrations/meta/webhook"
        next "the update line, so the api and the workers read them: $UPDATE_LINE"
      else
        info "nothing changed"
      fi
      ;;

    # -------------------------------------------------------------- webhook
    webhook)
      # Nothing secret is printed here: the verify token is the one the owner
      # made up and typed at the hidden prompt of the keys step; he types the
      # same string into Meta's dashboard.
      local host
      host="$(env_get SITE_HOST)"
      [ -n "$(env_get META_VERIFY_TOKEN)" ] || die "no verify token yet: $SELF_LINE keys (make one up and type it at the hidden prompt), then the update line, then this step again"
      say "In Meta's App Dashboard (your app > Webhooks), subscribe:"
      info "the Page object:      feed, messages, messaging_policy_enforcement"
      info "the Instagram object: comments, messages"
      info "  (messages carries a STOP sent in reply to the message; messaging_policy_enforcement Meta's warnings and blocks)"
      info "Callback URL:  https://${host:-afflino.com}/api/v1/integrations/meta/webhook"
      info "Verify token:  the one you made up at the keys step (type it again there; it is not shown here)"
      info "App settings > Basic > Data deletion: the callback URL https://${host:-afflino.com}/api/v1/integrations/meta/data-deletion"
      info "each Page's messaging response mode (Page settings > Messaging): hybrid, so a person answers what the automation does not"
      [ -n "$(env_get META_APP_SECRET)" ] || warn "no Meta app secret yet: $SELF_LINE keys (every delivery is refused with 503 until then)"
      info "then check it: $SELF_LINE reply-test"
      ;;

    # ----------------------------------------------------------- reply-test
    reply-test)
      stack_up
      say "The exact private reply for one look, through the stub sender (nothing is sent to Meta), and the webhook's own checks."
      local look out="$LIB/reply-test.json"
      look="$(ask "The look's id (the admin's look page, or its address on afflino.com): ")"
      look="${look%%\?*}"; look="${look%/}"; look="${look##*/}"
      printf '%s' "$look" | grep -Eq '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' || die "'$look' is not a look id; nothing was sent"
      install -d -m 0755 "$LIB"
      cli reply-test --look "$look" --webhook http://api:3000 >"$out" || die "the test did not run (the reason is above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
print(f"   look public now: {'yes' if s['look_public'] else 'no (a reply is sent only while the look is public)'}")
print(f"   replies may go out for it: {'yes' if s.get('look_sendable') else 'no (only while the look is public AND carries products on a live offer)'}")
if s["dm_text"]:
    print(f"   the private reply ({s['dm_bytes']} of 1000 bytes), exactly:")
    for line in s["dm_text"].splitlines():
        print(f"     | {line}")
else:
    print(f"   NOT SENDABLE: {s['dm_refusal']}")
print(f"   stub sender: {s['stub_sender']['private_replies']} private repl(y/ies) recorded, {s['stub_sender']['sent_to_meta']} sent to Meta")
for r in s["rules"]:
    print(f"   rule {r['id']}: {'on' if r['enabled'] else 'off'}, keywords {', '.join(r['keywords'])}")
if not s["rules"]:
    print("   no comment-reply rule for this look yet (the admin: Comment replies)")
w = s.get("webhook") or {}
for k in ["verify", "verify_wrong_token", "signed_delivery", "wrongly_signed_delivery", "messaging_stop"]:
    if k in w:
        print(f"   webhook {k.replace('_', ' ')}: {w[k]}")
if "events_stored_for_test_account" in w:
    print(f"   events stored for the TEST account: {w['events_stored_for_test_account']}")
PY
      ;;

    # --------------------------------------------------------------- events
    events)
      stack_up
      install -d -m 0755 "$LIB"
      local out="$LIB/events.json"
      cli events --limit 20 >"$out" || die "no events (above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
items = json.load(open(sys.argv[1]))["items"]
if not items:
    print("   no comment-reply event yet")
for e in items:
    code = f" ({e['error_code']})" if e["error_code"] else ""
    print(f"   {e['received_at'][:16].replace('T', ' ')} UTC  {e['platform']}/{e['account']:<24} '{e['matched_keyword']}'  {e['status']}{code}")
PY
      info "no comment text, username or commenter id is stored or shown"
      ;;

    # --------------------------------------------------------------- signin
    signin)
      stack_up
      say "A sign-in for the admin (https://${AFFLINO_SIGNIN_HOST:-afflino.com}/login), valid 8 hours. It is written to a root-only file, never shown."
      local who role tokfile tmp
      who="$(ask 'Sign in as 1) the network admin (tagging, publishing), 2) the rights reviewer (counsel) or 3) the second editor (approves EXACT tags; a different person from the tagger)? (1/2/3): ')"
      case "$who" in 1) role=network_admin ;; 2) role=rights_reviewer ;; 3) role=editor ;; *) die "1, 2 or 3; nothing was made" ;; esac
      tokfile="$(dirname "$ENV_FILE")/admin-sign-in.token"
      tmp="$(mktemp "$(dirname "$ENV_FILE")/.sign-in.XXXXXX")"
      chmod 600 "$tmp"
      if ! cli sign-in --role "$role" --hours 8 >"$tmp"; then rm -f "$tmp"; die "no sign-in was made (above)"; fi
      ( umask 077; python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); open(sys.argv[2],"w").write(d["token"]); print("   " + d["role"].replace("_", " ") + ", valid until " + d["expires_at"][:16].replace("T", " ") + " UTC")' "$tmp" "$tokfile" )
      rm -f "$tmp"
      chmod 600 "$tokfile"
      info "written to $tokfile (root, 0600)"
      next "on your Mac, the line in docs/runbooks/deploy.md §1C copies it to the clipboard; paste it at /login"
      ;;

    # ------------------------------------------------------------- accounts
    accounts)
      stack_up
      if [ -z "$(env_get META_APP_SECRET)" ] || [ -z "$(env_get META_SYSTEM_USER_TOKEN)" ]; then die "no Meta keys yet: run $SELF_LINE keys, then the update line"; fi
      install -d -m 0755 "$LIB"
      local out="$LIB/accounts.json"
      dc run --rm --no-deps -T workers node dist/meta/sync-accounts-once.js --subscribe </dev/null >"$out" || die "the accounts check failed (above)"
      keep_json "$out"
      python3 - "$out" <<'PY'
import json, sys
s = json.load(open(sys.argv[1]))
print(f"   Meta lists {s['pages_seen']} page(s), {s['instagram_seen']} with an Instagram account")
print(f"   mapped: {s['mapped_facebook']} Facebook page(s), {s['mapped_instagram']} Instagram account(s); messaging ok {s['messaging_ok']}, off {s['messaging_disabled']}")
print(f"   page webhooks subscribed: {s['subscribed']} (failed {s['subscribe_failed']}); Instagram fields are set in Meta's App Dashboard")
u = s["unmatched_properties"]
if u["facebook"] or u["instagram"]:
    print(f"   not found at Meta (give the system user these pages): {len(u['facebook'])} Facebook, {len(u['instagram'])} Instagram, e.g. {', '.join((u['facebook'] + u['instagram'])[:5])}")
PY
      ;;

    # -------------------------------------------------------------- replies
    replies)
      local mode="${2:-}"
      case "$mode" in off|shadow|on) ;; *) die "usage: $SELF_LINE replies off|shadow|on" ;; esac
      stack_up
      if [ "$mode" = on ]; then
        if [ -z "$(env_get META_APP_SECRET)" ] || [ -z "$(env_get META_SYSTEM_USER_TOKEN)" ]; then die "no Meta keys yet: run $SELF_LINE keys first"; fi
        privacy_gate
      fi
      env_set COMMENT_REPLIES_SENDING "$mode"
      restart_workers
      case "$mode" in
        off) info "comment replies are off: nothing is sent" ;;
        shadow) info "comment replies in shadow: every check runs, nothing is sent (status skipped_shadow; $SELF_LINE status)" ;;
        on) info "comment replies are on: one private reply per matched comment, carrying only the look's afflino.com page" ;;
      esac
      ;;
  esac
}

main "$@"
