"""OpenSEO: search data for the writer and rank tracking for the fleet, over the self-hosted MCP server.

OpenSEO (github.com/every-app/open-seo) runs beside the fleet as the `openseo` service, on the internal
Docker network only (docker-compose.yml, generated by infra/gen_compose.py), with a DataForSEO key in
.env. It speaks MCP over HTTP at `OPENSEO_URL` (http://openseo:3001/mcp inside the fleet); this module is
a small MCP client for the few tools the fleet uses:

- `list_projects` / `create_project`: one OpenSEO project per site, keyed by domain, market India (2356).
- `research_keywords`: before an article is written, the story's own title is the seed and the keywords
  people actually search for come back with volume and difficulty; the best of them go to the writer as
  TARGET KEYWORDS for the title, slug, excerpt and first paragraph (`Rewriter.rewrite(keywords=...)`).
- `create_rank_tracker` / `add_rank_tracking_keywords` / `run_rank_tracker` / `get_rank_tracker`: the
  keywords the site has written for are tracked, on demand (`python -m autopub seo track`).

Without `OPENSEO_URL` nothing here runs and the pipeline writes as before. Every call costs DataForSEO
credits (research ~30-100 per seed), so the pipeline asks for one seed per article.
"""
from __future__ import annotations

import json
import logging
import os
import re
import time

import requests

log = logging.getLogger(__name__)

INDIA = 2356                    # DataForSEO location code
LANGUAGE = "en"
MAX_TARGETS = 5                 # keywords handed to the writer
MAX_DIFFICULTY = 60             # above this a new site will not rank; the keyword is not worth aiming at
TIMEOUT = 60
PROTOCOL = "2025-03-26"


def url() -> str | None:
    return (os.environ.get("OPENSEO_URL") or "").strip() or None


def enabled() -> bool:
    return url() is not None


class OpenSeoError(RuntimeError):
    pass


class Client:
    """MCP over streamable HTTP: initialize once, then tools/call. Answers may come as JSON or as an SSE
    stream; both are read. An API key (`OPENSEO_API_KEY`, for the hosted service) goes as a bearer."""

    def __init__(self, base: str | None = None, api_key: str | None = None, timeout: int = TIMEOUT):
        self.base = (base or url() or "").rstrip("/")
        if not self.base:
            raise OpenSeoError("OPENSEO_URL is not set")
        self.api_key = api_key if api_key is not None else (os.environ.get("OPENSEO_API_KEY") or "").strip()
        self.timeout = timeout
        self.session_id: str | None = None
        self._n = 0

    def _headers(self) -> dict:
        h = {"Content-Type": "application/json", "Accept": "application/json, text/event-stream", "MCP-Protocol-Version": PROTOCOL}
        if self.api_key:
            h["Authorization"] = f"Bearer {self.api_key}"
        if self.session_id:
            h["mcp-session-id"] = self.session_id
        return h

    def _post(self, payload: dict) -> dict | None:
        resp = requests.post(self.base, json=payload, headers=self._headers(), timeout=self.timeout)
        if resp.status_code >= 400:
            raise OpenSeoError(f"OpenSEO {resp.status_code}: {resp.text[:300]}")
        sid = resp.headers.get("mcp-session-id")
        if sid:
            self.session_id = sid
        if "id" not in payload:
            return None
        body = resp.text
        if resp.headers.get("content-type", "").startswith("text/event-stream"):
            messages = []
            for line in body.splitlines():
                if line.startswith("data:"):
                    try:
                        messages.append(json.loads(line[5:].strip()))
                    except json.JSONDecodeError:
                        continue
            answer = next((m for m in messages if isinstance(m, dict) and m.get("id") == payload["id"]), messages[-1] if messages else {})
        else:
            answer = json.loads(body) if body.strip() else {}
        if isinstance(answer, dict) and answer.get("error"):
            raise OpenSeoError(f"OpenSEO: {answer['error'].get('message') or answer['error']}")
        return answer.get("result") if isinstance(answer, dict) else None

    def _rpc(self, method: str, params: dict | None = None) -> dict | None:
        self._n += 1
        return self._post({"jsonrpc": "2.0", "id": self._n, "method": method, "params": params or {}})

    def connect(self) -> "Client":
        self._rpc("initialize", {"protocolVersion": PROTOCOL, "capabilities": {},
                                 "clientInfo": {"name": "autopub", "version": "1.0"}})
        self._post({"jsonrpc": "2.0", "method": "notifications/initialized"})
        return self

    def call(self, tool: str, arguments: dict | None = None) -> dict:
        """The tool's structured result (its `structuredContent`), or its text under `text` when it has none."""
        if self.session_id is None:
            self.connect()
        result = self._rpc("tools/call", {"name": tool, "arguments": arguments or {}}) or {}
        if result.get("isError"):
            text = " ".join(c.get("text", "") for c in result.get("content") or [] if isinstance(c, dict))
            raise OpenSeoError(f"{tool}: {text[:300] or 'tool error'}")
        structured = result.get("structuredContent")
        if isinstance(structured, dict):
            return structured
        return {"text": " ".join(c.get("text", "") for c in result.get("content") or [] if isinstance(c, dict))}

    def tools(self) -> list[str]:
        if self.session_id is None:
            self.connect()
        result = self._rpc("tools/list") or {}
        return [t.get("name", "") for t in result.get("tools") or []]


# ---- the fleet's use of it --------------------------------------------------------------------------

_PROJECTS: dict[str, str] = {}      # domain -> project id, for the run


def project_for(client: Client, name: str, domain: str) -> str:
    """The site's OpenSEO project id, created on first use with India as the market."""
    if domain in _PROJECTS:
        return _PROJECTS[domain]
    listed = client.call("list_projects").get("projects") or []
    for p in listed:
        if (p.get("domain") or "").lower().lstrip("www.") == domain.lower() and p.get("id"):
            _PROJECTS[domain] = p["id"]
            return p["id"]
    made = client.call("create_project", {"name": name, "domain": domain, "locationCode": INDIA, "languageCode": LANGUAGE})
    pid = made.get("id") or (made.get("project") or {}).get("id")
    if not pid:
        raise OpenSeoError(f"create_project returned no id: {str(made)[:200]}")
    _PROJECTS[domain] = pid
    log.info("openseo: project %s for %s", pid, domain)
    return pid


def seed_from(title: str) -> str:
    """A search seed from a story's title: quotes, bracketed asides and the publisher's flourish gone."""
    t = re.sub(r"[\"“”‘’'|:]+", " ", title or "")
    t = re.sub(r"\(.*?\)|\[.*?\]", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    words = t.split()
    return " ".join(words[:9]).lower()


def research(client: Client, project_id: str, seeds: list[str]) -> list[dict]:
    """Keywords for the seeds: keyword, volume, difficulty, intent; the strongest first."""
    seeds = [s for s in seeds if s][:5]
    if not seeds:
        return []
    got = client.call("research_keywords", {"projectId": project_id, "seeds": [{"seed": s} for s in seeds], "resultLimit": 150})
    rows: list[dict] = []
    for result in got.get("results") or []:
        if not result.get("ok"):
            log.info("openseo: seed %r failed: %s", result.get("seed"), result.get("error"))
            continue
        seed_words = {w for w in re.findall(r"[a-z0-9]+", (result.get("seed") or "").lower()) if len(w) > 1}
        for row in result.get("rows") or []:
            kw = (row.get("keyword") or "").strip()
            if kw:
                words = {w for w in re.findall(r"[a-z0-9]+", kw.lower()) if len(w) > 1}
                rows.append({"keyword": kw, "volume": row.get("searchVolume") or 0, "difficulty": row.get("keywordDifficulty"),
                             "intent": row.get("intent") or "", "seed": result.get("seed"),
                             "overlap": len(words & seed_words) / max(1, len(seed_words))})   # how much of the story it is about
    # about the story first (the primary keyword must be the story's, not the film's biggest query), then searched
    rows.sort(key=lambda r: (-round(r.get("overlap", 0), 1), -(r["volume"] or 0), r["difficulty"] if r["difficulty"] is not None else 101))
    return rows


def targets(rows: list[dict], limit: int = MAX_TARGETS) -> list[dict]:
    """The keywords worth writing for: searched, not too hard, one per phrasing."""
    out, seen = [], set()
    for r in rows:
        if not r["volume"] or (r["difficulty"] is not None and r["difficulty"] > MAX_DIFFICULTY):
            continue
        key = re.sub(r"[^a-z0-9]", "", r["keyword"].lower())
        if key in seen:
            continue
        seen.add(key)
        out.append(r)
        if len(out) >= limit:
            break
    return out


def brief(rows: list[dict]) -> str:
    """The TARGET KEYWORDS block for the writer's brief."""
    if not rows:
        return ""
    lines = "\n".join(f"- {r['keyword']} ({int(r['volume'] or 0)} searches/month" + (f", difficulty {int(r['difficulty'])}" if r.get("difficulty") is not None else "")
                      + (f", {r['intent']}" if r.get("intent") else "") + ")" for r in rows)
    return ("TARGET KEYWORDS (what people actually search, from OpenSEO; the first is primary): use the primary keyword "
            "naturally in the title, the slug, the excerpt and the first paragraph, and the others where they read naturally; "
            "never stuff them.\n" + lines + "\n\n")


def keywords_for_story(site_name: str, domain: str, title: str, timeout: int = TIMEOUT) -> list[dict]:
    """The pipeline's one call: the story's seed researched, the targets back; [] on any failure."""
    if not enabled():
        return []
    try:
        client = Client(timeout=timeout)
        pid = project_for(client, site_name, domain)
        rows = research(client, pid, [seed_from(title)])
        chosen = targets(rows)
        log.info("openseo: %d keywords for %r, %d targets", len(rows), seed_from(title), len(chosen))
        return chosen
    except Exception as exc:  # noqa: BLE001 - search data is a bonus; the article is written without it
        log.warning("openseo lookup failed (%s); writing without target keywords", exc)
        return []


# ---- rank tracking ----------------------------------------------------------------------------------

def tracker_for(client: Client, project_id: str, domain: str) -> str:
    """The project's rank tracker id, created when it has none."""
    got = client.call("get_rank_tracker", {"projectId": project_id})
    tid = got.get("id") or (got.get("tracker") or {}).get("id") or got.get("trackerId")
    if tid:
        return tid
    made = client.call("create_rank_tracker", {"projectId": project_id, "domain": domain, "locationCode": INDIA, "languageCode": LANGUAGE, "devices": "mobile"})
    tid = made.get("id") or (made.get("tracker") or {}).get("id") or made.get("trackerId")
    if not tid:
        raise OpenSeoError(f"create_rank_tracker returned no id: {str(made)[:200]}")
    return tid


def track(client: Client, project_id: str, domain: str, keywords: list[str], run: bool = True, max_cost: int = 2000) -> dict:
    """Track `keywords` for the domain and, when `run`, check the rankings now (credits)."""
    tid = tracker_for(client, project_id, domain)
    if keywords:
        client.call("add_rank_tracking_keywords", {"projectId": project_id, "trackerId": tid, "keywords": keywords[:2000]})
    if run:
        client.call("run_rank_tracker", {"projectId": project_id, "trackerId": tid, "maxCostCredits": max_cost})
        time.sleep(2)
    return client.call("get_rank_tracker", {"projectId": project_id, "trackerId": tid})
